services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    container_name: tts-announce
    restart: unless-stopped
    ports:
      - 8083:3000
    networks:
      - piper
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./data/chimes:/chimes:ro
      - ./data/cache:/cache

networks:
  piper:
    external: true
